name: globalcovid19info
on:
  schedule:
    - cron:  '0 6 * * *' 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
        env: 
 NEXT_PUBLIC_GOOGLE_SHEETS_CLIENT_EMAIL: ${{secrets.NEXT_PUBLIC_GOOGLE_SHEETS_CLIENT_EMAIL}} 
NEXT_PUBLIC_GOOGLE_SHEETS_PRIVATE_KEY: ${{secrets.NEXT_PUBLIC_GOOGLE_SHEETS_PRIVATE_KEY}} 
NEXT_PUBLIC_SPREADSHEET_ID: ${{secrets.NEXT_PUBLIC_SPREADSHEET_ID}} 
NEXT_PUBLIC_FIREBASE_APIKEY: ${{secrets.NEXT_PUBLIC_FIREBASE_APIKEY}} 
NEXT_PUBLIC_FIREBASE_AUTHDOMAIN: ${{secrets.NEXT_PUBLIC_FIREBASE_AUTHDOMAIN}} 
NEXT_PUBLIC_FIREBASE_PROJECTID: ${{secrets.NEXT_PUBLIC_FIREBASE_PROJECTID}} 
NEXT_PUBLIC_FIREBASE_STORAGEBUCKET: ${{secrets.NEXT_PUBLIC_FIREBASE_STORAGEBUCKET}} 
NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID: ${{secrets.NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID}} 
NEXT_PUBLIC_FIREBASE_APPID: ${{secrets.NEXT_PUBLIC_FIREBASE_APPID}} 
NEXT_PUBLIC_FIREBASE_MEASUREMENTID: ${{secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENTID}}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}